package entity;
// Generated Oct 18, 2016 5:58:45 PM by Hibernate Tools 4.3.1



/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private String username;
     private String password;
     private String hoten;
     private String gioitinh;
     private String email;
     private String role;
     private String anh;

    public Customer() {
    }

	
    public Customer(String username, String password) {
        this.username = username;
        this.password = password;
    }
    public Customer(String username, String password, String hoten, String gioitinh, String email, String role, String anh) {
       this.username = username;
       this.password = password;
       this.hoten = hoten;
       this.gioitinh = gioitinh;
       this.email = email;
       this.role = role;
       this.anh = anh;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }
    public String getGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(String gioitinh) {
        this.gioitinh = gioitinh;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public String getAnh() {
        return this.anh;
    }
    
    public void setAnh(String anh) {
        this.anh = anh;
    }




}


